# Generated by Django 6.0.1 on 2026-01-27 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos', models.CharField(max_length=60)),
                ('nombres', models.CharField(max_length=60)),
                ('nacionalidad', models.CharField(max_length=20)),
                ('lugarnacimiento', models.CharField(max_length=60)),
                ('fechanacimiento', models.DateField()),
                ('numerocedula', models.CharField(max_length=10, unique=True)),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1)),
                ('estadocivil', models.CharField(max_length=50)),
                ('licenciaconducir', models.CharField(blank=True, max_length=6)),
                ('telefonoconvencional', models.CharField(blank=True, max_length=15)),
                ('telefonofijo', models.CharField(max_length=15)),
                ('direcciontrabajo', models.CharField(blank=True, max_length=50)),
                ('direcciondomiciliaria', models.CharField(max_length=50)),
                ('sitioweb', models.URLField(blank=True, max_length=100)),
                ('universidad', models.CharField(default='Universidad Laica Eloy Alfaro de Manabí', max_length=100)),
                ('carrera', models.CharField(default='Tecnología de la información', max_length=100)),
                ('periodo_u', models.CharField(default='Mayo 2024 - En curso', max_length=50)),
                ('bachillerato_status', models.CharField(default='Bachillerato - completo', max_length=100)),
                ('certificado_bachiller_pdf', models.FileField(blank=True, null=True, upload_to='certificados/')),
                ('aptitudes', models.TextField(help_text='Separa tus habilidades por comas (ej: Python, SQL, Redes)')),
            ],
        ),
        migrations.CreateModel(
            name='CursoRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecurso', models.CharField(max_length=150)),
                ('nombreinstitucion', models.CharField(max_length=100)),
                ('numerohoras', models.IntegerField()),
                ('fechaobtencion', models.DateField()),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hv_app.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargodesempenado', models.CharField(max_length=100)),
                ('nombrempresa', models.CharField(max_length=50)),
                ('fechainicio', models.DateField()),
                ('fechafin', models.DateField(blank=True, null=True)),
                ('actividadesrealizadas', models.TextField()),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hv_app.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrerecurso', models.CharField(max_length=100)),
                ('clasificador', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hv_app.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreproducto', models.CharField(max_length=100)),
                ('fechaproducto', models.DateField()),
                ('descripcion', models.CharField(max_length=100)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hv_app.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='Reconocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrereconocimiento', models.CharField(max_length=100)),
                ('institucionqueotorga', models.CharField(max_length=100)),
                ('fechareconocimiento', models.DateField()),
                ('descripcion', models.CharField(max_length=100)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hv_app.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='VentaGarage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreproducto', models.CharField(max_length=100)),
                ('estadoproducto', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=100)),
                ('valordelbien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hv_app.datospersonales')),
            ],
        ),
    ]
