# Generated by Django 6.0.1 on 2026-01-27 21:59

import hv_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hv_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursorealizado',
            name='fechaobtencion',
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='direcciontrabajo',
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='licenciaconducir',
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='telefonoconvencional',
        ),
        migrations.RemoveField(
            model_name='productolaboral',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='reconocimiento',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='ventagarage',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='cursorealizado',
            name='certificado_pdf',
            field=models.FileField(blank=True, null=True, upload_to='cursos/'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='sobre_mi',
            field=models.TextField(blank=True, help_text='Descripción breve para tu CV'),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='reconocimientos/'),
        ),
        migrations.AddField(
            model_name='ventagarage',
            name='foto_producto',
            field=models.ImageField(blank=True, null=True, upload_to='garage/'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='aptitudes',
            field=models.TextField(help_text='Separa por comas: Python, SQL, Redes'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='bachillerato_status',
            field=models.CharField(default='Bachillerato - Completo', max_length=100),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='carrera',
            field=models.CharField(default='Tecnología de la Información', max_length=100),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='direcciondomiciliaria',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='fechanacimiento',
            field=models.DateField(validators=[hv_app.models.validar_fecha_no_futura]),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='fechafin',
            field=models.DateField(blank=True, null=True, validators=[hv_app.models.validar_fecha_no_futura]),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='fechainicio',
            field=models.DateField(validators=[hv_app.models.validar_fecha_no_futura]),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='nombrempresa',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productoacademico',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='productolaboral',
            name='fechaproducto',
            field=models.DateField(validators=[hv_app.models.validar_fecha_no_futura]),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='fechareconocimiento',
            field=models.DateField(validators=[hv_app.models.validar_fecha_no_futura]),
        ),
    ]
