# Generated by Django 6.0.1 on 2026-01-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hv_app', '0002_remove_cursorealizado_fechaobtencion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='direcciontrabajo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='licenciaconducir',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='telefonoconvencional',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='aptitudes',
            field=models.TextField(help_text='Separa tus habilidades por comas'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='sobre_mi',
            field=models.TextField(help_text='Perfil profesional o descripción breve'),
        ),
    ]
