# Generated by Django 6.0.1 on 2026-01-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hv_app', '0003_datospersonales_direcciontrabajo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reconocimiento',
            old_name='archivo_adjunto',
            new_name='comprobante_archivo',
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='sobre_mi',
            field=models.TextField(help_text='Escribe algo sobre ti (Acerca de mí)'),
        ),
    ]
