# Generated by Django 6.0.1 on 2026-01-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hv_app', '0004_rename_archivo_adjunto_reconocimiento_comprobante_archivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursorealizado',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Escribe qué aprendiste si no tienes el certificado PDF', null=True),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Se mostrará si no hay archivo adjunto', null=True),
        ),
    ]
