# Generated by Django 6.0.1 on 2026-01-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hv_app', '0006_productolaboral_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventagarage',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Detalles del artículo', null=True),
        ),
    ]
